name: Extract interface files from CDN

on:
  schedule:
    - cron: '0 0/3 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Export UI source files
        uses: Gethe/wow-ui-source@automation
        with:
          product: wow_classic
          token: ${{ secrets.GITHUB_TOKEN }}
